/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login do administrador
         * @description Recebe usuário e senha (form OAuth2) e devolve um JWT de acesso.
         */
        post: operations["login_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário da sessão atual */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo paginado */
        get: operations["list_movies_api_v1_movies_get"];
        put?: never;
        /** Cadastra um filme */
        post: operations["create_movie_api_v1_movies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/movies/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhes completos de um filme */
        get: operations["get_movie_api_v1_movies__movie_id__get"];
        put?: never;
        post?: never;
        /** Remove um filme e suas avaliações */
        delete: operations["delete_movie_api_v1_movies__movie_id__delete"];
        options?: never;
        head?: never;
        /** Atualiza um filme (parcial) */
        patch: operations["update_movie_api_v1_movies__movie_id__patch"];
        trace?: never;
    };
    "/api/v1/movies/{movie_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de avaliações, mais recentes primeiro */
        get: operations["list_movie_reviews_api_v1_movies__movie_id__reviews_get"];
        put?: never;
        /** Adiciona uma avaliação (nota de 0 a 10 e resenha) */
        post: operations["create_review_api_v1_movies__movie_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gêneros disponíveis */
        get: operations["list_genres_api_v1_genres_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca de pessoas (autocomplete) */
        get: operations["search_people_api_v1_people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_token_post */
        Body_login_api_v1_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** GenreOut */
        GenreOut: {
            /** Id */
            id: string;
            /** Nome */
            nome: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Me */
        Me: {
            /** Username */
            username: string;
        };
        /**
         * MovieCreate
         * @description Cadastro de filme.
         *
         *     A obrigatoriedade segue o modelo de dados (como a atividade orienta para a
         *     escala de notas): só o título é NOT NULL em ``dim_movies``. Os demais campos
         *     são opcionais, mas validados quando enviados. Informando só a data de
         *     lançamento, o ano é preenchido a partir dela.
         * @example {
         *       "ano_lancamento": 2024,
         *       "diretores": [
         *         "Walter Salles"
         *       ],
         *       "duracao_minutos": 137,
         *       "generos": [
         *         "Drama",
         *         "History"
         *       ],
         *       "sinopse": "Uma mulher reconstrói a vida após o desaparecimento do marido.",
         *       "status_filme": "Lançado",
         *       "titulo": "Ainda Estou Aqui"
         *     }
         */
        MovieCreate: {
            /** Titulo */
            titulo: string;
            /** Ano Lancamento */
            ano_lancamento?: number | null;
            /**
             * Generos
             * @description Nomes; reaproveita gêneros existentes (GET /genres) ou cria novos
             */
            generos?: string[];
            /**
             * Diretores
             * @description Nomes; reaproveita diretores existentes
             */
            diretores?: string[];
            /** Sinopse */
            sinopse?: string | null;
            /** Data Lancamento */
            data_lancamento?: string | null;
            /** Duracao Minutos */
            duracao_minutos?: number | null;
            status_filme?: components["schemas"]["MovieStatus"] | null;
            /** Url Poster */
            url_poster?: string | null;
            /** Url Backdrop */
            url_backdrop?: string | null;
        };
        /**
         * MovieDetail
         * @description Informações completas de um filme.
         */
        MovieDetail: {
            /** Id */
            id: string;
            /** Id Filme */
            id_filme: string;
            /** Titulo */
            titulo: string;
            /** Data Lancamento */
            data_lancamento: string | null;
            /** Ano Lancamento */
            ano_lancamento: number | null;
            /** Duracao Minutos */
            duracao_minutos: number | null;
            /** Status Filme */
            status_filme: string | null;
            /** Sinopse */
            sinopse: string | null;
            /** Url Poster */
            url_poster: string | null;
            /** Url Backdrop */
            url_backdrop: string | null;
            /** Generos */
            generos: components["schemas"]["GenreOut"][];
            /** Diretores */
            diretores: components["schemas"]["PersonOut"][];
            /** Roteiristas */
            roteiristas: components["schemas"]["PersonOut"][];
            /** Elenco */
            elenco: components["schemas"]["PersonOut"][];
            /** Produtoras */
            produtoras: string[];
            desempenho: components["schemas"]["PerformanceOut"] | null;
            avaliacao: components["schemas"]["RatingSummary"];
        };
        /**
         * MovieListItem
         * @description Resumo de um filme para cards do catálogo.
         */
        MovieListItem: {
            /** Id */
            id: string;
            /** Titulo */
            titulo: string;
            /** Ano Lancamento */
            ano_lancamento: number | null;
            /** Url Poster */
            url_poster: string | null;
            /** Generos */
            generos: string[];
            avaliacao: components["schemas"]["RatingSummary"];
        };
        /**
         * MovieSort
         * @description Ordenações disponíveis no catálogo.
         * @enum {string}
         */
        MovieSort: "popularidade" | "titulo" | "-ano" | "ano" | "-media" | "-avaliacoes";
        /**
         * MovieStatus
         * @description Situações presentes no catálogo original.
         * @enum {string}
         */
        MovieStatus: "Lançado" | "Pós-Produção" | "Em Produção" | "Planejado";
        /**
         * MovieUpdate
         * @description Atualização parcial: só os campos enviados são alterados.
         *
         *     Mesmas regras do cadastro: o título não pode ser removido; campos opcionais
         *     podem ser limpos com ``null`` (ou ``[]`` para gêneros e diretores).
         * @example {
         *       "duracao_minutos": 140
         *     }
         */
        MovieUpdate: {
            /** Titulo */
            titulo?: string | null;
            /** Ano Lancamento */
            ano_lancamento?: number | null;
            /** Generos */
            generos?: string[] | null;
            /** Diretores */
            diretores?: string[] | null;
            /** Sinopse */
            sinopse?: string | null;
            /** Data Lancamento */
            data_lancamento?: string | null;
            /** Duracao Minutos */
            duracao_minutos?: number | null;
            status_filme?: components["schemas"]["MovieStatus"] | null;
            /** Url Poster */
            url_poster?: string | null;
            /** Url Backdrop */
            url_backdrop?: string | null;
        };
        /** Page[MovieListItem] */
        Page_MovieListItem_: {
            /** Items */
            items: components["schemas"]["MovieListItem"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Pages
             * @description Total de páginas
             */
            pages: number;
        };
        /** Page[ReviewOut] */
        Page_ReviewOut_: {
            /** Items */
            items: components["schemas"]["ReviewOut"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Pages
             * @description Total de páginas
             */
            pages: number;
        };
        /** PerformanceOut */
        PerformanceOut: {
            /** Orcamento Usd */
            orcamento_usd: number | null;
            /** Receita Usd */
            receita_usd: number | null;
            /** Lucro Usd */
            lucro_usd: number | null;
            /** Orcamento Brl */
            orcamento_brl: number | null;
            /** Receita Brl */
            receita_brl: number | null;
            /** Lucro Brl */
            lucro_brl: number | null;
            /** Popularidade */
            popularidade: number | null;
            /** Nota Tmdb */
            nota_tmdb: number | null;
            /** Qtd Tmdb */
            qtd_tmdb: number | null;
            /** Nota Imdb */
            nota_imdb: number | null;
            /** Qtd Imdb */
            qtd_imdb: number | null;
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "Ator" | "Diretor" | "Roteirista";
        };
        /**
         * RatingSummary
         * @description Média geral (escala 0–10) e total de avaliações de um filme.
         */
        RatingSummary: {
            /**
             * Media
             * @description Média das notas, arredondada em 2 casas
             */
            media: number | null;
            /** Qtd Avaliacoes */
            qtd_avaliacoes: number;
        };
        /**
         * ReviewCreate
         * @description Nova avaliação: nota de 0 a 10 e resenha em texto.
         * @example {
         *       "comentario": "Atuações excelentes.",
         *       "nome": "Maria",
         *       "nota": 8.5
         *     }
         */
        ReviewCreate: {
            /** Nome */
            nome: string;
            /**
             * Nota
             * @description Escala de 0 a 10
             */
            nota: number;
            /** Comentario */
            comentario: string;
        };
        /**
         * ReviewCreated
         * @description Avaliação criada e o resumo do filme já recalculado.
         */
        ReviewCreated: {
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Nota */
            nota: number;
            /** Comentario */
            comentario: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            avaliacao: components["schemas"]["RatingSummary"];
        };
        /** ReviewOut */
        ReviewOut: {
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Nota */
            nota: number;
            /** Comentario */
            comentario: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Usuário ou senha inválidos */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_movies_api_v1_movies_get: {
        parameters: {
            query?: {
                /** @description Página, começando em 1 */
                page?: number;
                /** @description Itens por página (máx. 100) */
                page_size?: number;
                /** @description Busca por título ou diretor (ignora acentos) */
                q?: string | null;
                /** @description ID do gênero (GET /genres) */
                genre?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                sort?: components["schemas"]["MovieSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MovieListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_movie_api_v1_movies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetail"];
                };
            };
            /** @description Requer login do administrador */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos ou inconsistentes com o catálogo */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_movie_api_v1_movies__movie_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetail"];
                };
            };
            /** @description Filme não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_movie_api_v1_movies__movie_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requer login do administrador */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Filme não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_movie_api_v1_movies__movie_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetail"];
                };
            };
            /** @description Requer login do administrador */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Filme não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos ou inconsistentes com o catálogo */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_movie_reviews_api_v1_movies__movie_id__reviews_get: {
        parameters: {
            query?: {
                /** @description Página, começando em 1 */
                page?: number;
                /** @description Itens por página (máx. 100) */
                page_size?: number;
            };
            header?: never;
            path: {
                movie_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReviewOut_"];
                };
            };
            /** @description Filme não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_movies__movie_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCreated"];
                };
            };
            /** @description Requer login do administrador */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Filme não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_genres_api_v1_genres_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreOut"][];
                };
            };
        };
    };
    search_people_api_v1_people_get: {
        parameters: {
            query?: {
                q?: string | null;
                tipo?: ("Ator" | "Diretor" | "Roteirista") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
